# Generated by Django 2.2 on 2022-03-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('lGA', models.CharField(blank=True, max_length=100)),
                ('state_of_Origin', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('school_attended', models.CharField(blank=True, max_length=100)),
                ('Last_Class_passed', models.CharField(blank=True, max_length=100)),
                ('common_Ent_Exam_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('agg_Score', models.CharField(blank=True, max_length=100, null=True)),
                ('class_applying_for', models.CharField(blank=True, max_length=100)),
                ('disability', models.CharField(blank=True, max_length=100)),
                ('specify', models.CharField(blank=True, max_length=200, null=True)),
                ('i_certify_that_the_information_given_above_are_the_truth_and_nothing_but_the_truth', models.BooleanField(blank=True, default=False, null=True)),
                ('parents_Name', models.CharField(blank=True, max_length=100)),
                ('addressp', models.CharField(blank=True, max_length=100)),
                ('phone_numberp', models.CharField(blank=True, max_length=100)),
                ('townp', models.CharField(blank=True, max_length=100)),
                ('lGAp', models.CharField(blank=True, max_length=100)),
                ('state_of_Originp', models.CharField(blank=True, max_length=100)),
                ('Are_you_ready_to_cooperate_with_the_School_or_PTA_for_the_proper_upbringing_of_your_Child', models.CharField(blank=True, max_length=100)),
                ('Are_you_ready_to_pay_all_the_approved_fees_as_at_when_due', models.CharField(blank=True, max_length=100)),
                ('Is_your_Child_ready_to_obey_all_the_school_Rules_and_Regulations', models.CharField(blank=True, max_length=100)),
                ('Admitted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
