# Generated by Django 2.2 on 2022-03-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Admitted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Are_you_ready_to_cooperate_with_the_School_or_PTA_for_the_proper_upbringing_of_your_Child',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Are_you_ready_to_pay_all_the_approved_fees_as_at_when_due',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Is_your_Child_ready_to_obey_all_the_school_Rules_and_Regulations',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='disability',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='i_certify_that_the_information_given_above_are_the_truth_and_nothing_but_the_truth',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
