# Generated by Django 2.2 on 2022-03-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Name',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Amount',
            new_name='Payment_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='Name_of_student',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
