# Generated by Django 2.2 on 2022-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0005_auto_20220315_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
