# Generated by Django 2.2 on 2022-03-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Excelfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Excel', models.FileField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.IntegerField(blank=True)),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Class', models.CharField(blank=True, max_length=10)),
                ('Academicsession', models.CharField(blank=True, max_length=20)),
                ('Subject', models.CharField(blank=True, max_length=100)),
                ('FirstTest', models.IntegerField(blank=True)),
                ('SecondTest', models.IntegerField(blank=True)),
                ('Project', models.IntegerField(blank=True)),
                ('MidTermTest', models.IntegerField(blank=True)),
                ('FirstAss', models.IntegerField(blank=True)),
                ('SecondAss', models.IntegerField(blank=True)),
                ('CA', models.IntegerField(blank=True)),
                ('Exam', models.IntegerField(blank=True)),
                ('Total', models.IntegerField(blank=True)),
                ('Grade', models.CharField(blank=True, max_length=2)),
                ('Position', models.CharField(blank=True, max_length=5)),
                ('Remark', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Studentlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Class', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
