# Generated by Django 2.2 on 2022-03-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.IntegerField(blank=True)),
                ('Name', models.CharField(blank=True, max_length=50)),
                ('Class', models.CharField(blank=True, max_length=10)),
                ('Term', models.CharField(blank=True, max_length=15)),
                ('Academicsession', models.CharField(blank=True, max_length=20)),
                ('Subject', models.CharField(blank=True, max_length=100)),
                ('FirstTest', models.IntegerField(blank=True)),
                ('SecondTest', models.IntegerField(blank=True)),
                ('Project', models.IntegerField(blank=True)),
                ('MidTermTest', models.IntegerField(blank=True)),
                ('FirstAss', models.IntegerField(blank=True)),
                ('SecondAss', models.IntegerField(blank=True)),
                ('CA', models.IntegerField(blank=True)),
                ('Exam', models.IntegerField(blank=True)),
                ('Total', models.IntegerField(blank=True)),
                ('Grade', models.CharField(blank=True, max_length=2)),
                ('SubjectPosition', models.CharField(blank=True, max_length=5)),
                ('Remark', models.CharField(blank=True, max_length=15)),
                ('Position', models.CharField(blank=True, max_length=15)),
                ('Average', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='Classlist',
            new_name='Class',
        ),
        migrations.DeleteModel(
            name='Studentlist',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Academicsession',
        ),
        migrations.RemoveField(
            model_name='student',
            name='CA',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Exam',
        ),
        migrations.RemoveField(
            model_name='student',
            name='FirstAss',
        ),
        migrations.RemoveField(
            model_name='student',
            name='FirstTest',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='MidTermTest',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Position',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Remark',
        ),
        migrations.RemoveField(
            model_name='student',
            name='SN',
        ),
        migrations.RemoveField(
            model_name='student',
            name='SecondAss',
        ),
        migrations.RemoveField(
            model_name='student',
            name='SecondTest',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Total',
        ),
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
