# Generated by Django 2.2 on 2022-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin',
            field=models.BigIntegerField(),
        ),
    ]
