# Generated by Django 2.2 on 2022-03-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0002_auto_20220305_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='Average',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Position',
        ),
        migrations.AddField(
            model_name='student',
            name='Average',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='Position',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
