# Generated by Django 2.2 on 2022-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0002_auto_20220404_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Password',
        ),
        migrations.AlterField(
            model_name='result',
            name='Class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='result',
            name='Remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='SubjectPosition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Academicsession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Average',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='Position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Term',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
