# Generated by Django 2.2 on 2022-04-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0003_auto_20220404_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='student',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
