# Generated by Django 2.2 on 2022-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0003_auto_20220305_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.ImageField(blank=True, upload_to='assets')),
            ],
        ),
    ]
