# Generated by Django 2.2 on 2022-12-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0004_auto_20221224_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_pin_and_id',
            name='SN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students_pin_and_id',
            name='student_class',
            field=models.CharField(blank=True, default='No class', max_length=100),
        ),
    ]
