# Generated by Django 2.2 on 2022-04-12 23:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0004_pin_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='Picture',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='newsletter',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
