# Generated by Django 2.2 on 2022-03-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0004_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='Academicsession',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Term',
        ),
        migrations.AddField(
            model_name='student',
            name='Academicsession',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='Term',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
