# Generated by Django 2.2 on 2022-04-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0005_auto_20220412_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='TotalScore',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
