# Generated by Django 2.2 on 2022-12-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0006_auto_20221224_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Class',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
