# Generated by Django 2.2 on 2022-04-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0006_student_totalscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Totalnumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
