# Generated by Django 2.2 on 2022-03-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0006_auto_20220307_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='CA',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Exam',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='FirstAss',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='FirstTest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Grade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='MidTermTest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Project',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='SN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='SecondAss',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='SecondTest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Total',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
