# Generated by Django 2.2 on 2023-04-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0007_auto_20221230_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualresult',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='annualstudent',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Name',
        ),
        migrations.AddField(
            model_name='annualresult',
            name='Student_id',
            field=models.CharField(blank=True, default='No id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='student_name',
            field=models.CharField(blank=True, default='No name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='annualstudent',
            name='Student_id',
            field=models.CharField(blank=True, default='No id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='annualstudent',
            name='student_name',
            field=models.CharField(blank=True, default='No name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='Student_id',
            field=models.CharField(blank=True, default='No id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='student_name',
            field=models.CharField(blank=True, default='No name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Student_id',
            field=models.CharField(blank=True, default='No id', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, default='No name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='students_pin_and_id',
            name='student_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='assets/Students'),
        ),
        migrations.AddField(
            model_name='students_pin_and_id',
            name='student_password',
            field=models.CharField(blank=True, default='No password', max_length=100, null=True),
        ),
    ]
