# Generated by Django 2.2 on 2023-11-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0009_auto_20230905_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Result_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalScore', models.CharField(blank=True, default='-', max_length=100)),
                ('Totalnumber', models.CharField(blank=True, default='-', max_length=100)),
                ('Average', models.CharField(blank=True, default='-', max_length=100)),
                ('Position', models.CharField(blank=True, default='-', max_length=100)),
                ('Remark', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('Academicsession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SRMS.AcademicSession')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=100)),
                ('academicsession', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SRMS.AcademicSession')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='FirstTerm',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='SN',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='SecondTerm',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='Student_id',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='ThirdTerm',
        ),
        migrations.RemoveField(
            model_name='annualresult',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='annualstudent',
            name='Academicsession',
        ),
        migrations.RemoveField(
            model_name='annualstudent',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='annualstudent',
            name='Student_id',
        ),
        migrations.RemoveField(
            model_name='annualstudent',
            name='Term',
        ),
        migrations.RemoveField(
            model_name='annualstudent',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='result',
            name='SN',
        ),
        migrations.RemoveField(
            model_name='result',
            name='Student_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='student_name',
        ),
        migrations.AddField(
            model_name='annualresult',
            name='FirstTermTotal',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='SecondTermTotal',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='ThirdTermTotal',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annualresult',
            name='students_result_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SRMS.AnnualStudent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annualstudent',
            name='Student_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SRMS.Students_Pin_and_ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students_pin_and_id',
            name='Sex',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='Average',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='Grade',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='Remark',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRMS.Subject'),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='SubjectPosition',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='annualresult',
            name='Total',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='CA',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Exam',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='FirstAss',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='FirstTest',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Grade',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='MidTermTest',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Project',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Remark',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='SecondAss',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='SecondTest',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRMS.Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='SubjectPosition',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='Total',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='student_result_data',
            name='Student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRMS.Students_Pin_and_ID'),
        ),
        migrations.AddField(
            model_name='student_result_data',
            name='Term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SRMS.Term'),
        ),
        migrations.AddField(
            model_name='result',
            name='students_result_summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SRMS.Student_Result_Data'),
        ),
    ]
