# Generated by Django 2.2 on 2023-11-25 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0011_auto_20231125_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_pin_and_id',
            name='student_class',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='SRMS.Class'),
        ),
    ]
