# Generated by Django 2.2 on 2023-11-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0012_auto_20231125_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjectallocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SRMS.Class')),
                ('subjects', models.ManyToManyField(to='SRMS.Subject')),
            ],
        ),
    ]
