# Generated by Django 2.2 on 2023-11-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0013_subjectallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_pin_and_id',
            name='student_pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
