# Generated by Django 2.2 on 2024-07-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0015_auto_20240725_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualresult',
            name='students_result_data',
        ),
        migrations.AddField(
            model_name='annualresult',
            name='Student_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SRMS.Students_Pin_and_ID'),
        ),
    ]
