# Generated by Django 2.2 on 2024-12-02 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0018_auto_20240729_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRMS.AcademicSession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRMS.Students_Pin_and_ID')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRMS.Class')),
            ],
        ),
    ]
