# Generated by Django 2.2 on 2024-12-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0020_auto_20241202_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_pin_and_id',
            name='student_class',
        ),
    ]
