# Generated by Django 2.2 on 2022-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='questionnumber',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
