# Generated by Django 2.2 on 2022-03-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='Mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='Vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
