# Generated by Django 2.2 on 2024-08-27 10:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carouselitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.AddField(
            model_name='school',
            name='SchoolAbout',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='SchoolAimsandObjectives',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='SchoolMission',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='SchoolVision',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
