# Generated by Django 2.2 on 2023-04-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faq_questionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogallery',
            name='Photo',
            field=models.ImageField(upload_to='assets/Photogallery'),
        ),
        migrations.AlterField(
            model_name='school',
            name='Schoollogo',
            field=models.ImageField(blank=True, upload_to='assets/Schoollogo'),
        ),
        migrations.AlterField(
            model_name='upcomingevents',
            name='Flier',
            field=models.ImageField(blank=True, upload_to='assets/Eventsflier'),
        ),
    ]
