# Generated by Django 2.2 on 2022-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='Ebook',
            field=models.FileField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Icon',
            field=models.ImageField(blank=True, upload_to='assets'),
        ),
    ]
