# Generated by Django 2.2 on 2023-11-24 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRMS', '0010_auto_20231124_1140'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Class_assigned',
            new_name='teachers_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Facebook_link',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Instagram_link',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Twitter_link',
        ),
        migrations.AddField(
            model_name='teacher',
            name='FirstName',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='LastName',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classFormed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SRMS.Class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes_taught',
            field=models.ManyToManyField(related_name='assigned_classes', to='SRMS.Class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects_taught',
            field=models.ManyToManyField(to='SRMS.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Headshot',
            field=models.ImageField(blank=True, upload_to='assets/TeachersProfileimages'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Formteacher', 'Formteacher'), ('Admin', 'Admin')], default='Teacher', max_length=200),
        ),
    ]
