# Generated by Django 2.2 on 2024-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMS', '0003_auto_20231125_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Role',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Formteacher', 'Formteacher'), ('Admin', 'Admin')], default='Teacher', max_length=200),
        ),
    ]
